name: Olá Mundo!!

on:
  push:

jobs:
  ola_mundo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v4

      - name: Exibir mensagem
        run: echo "Olá, Mundo!"
